# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileNotice: Part of the FreeCAD project.

#
#   Configure to scan the Python constraints files.
#

version : 2

updates:

    -   package-ecosystem : 'pip'
        directory : '/Data/Python/Constraints'

        schedule:
            interval : 'weekly'

        groups:
            all-deps:
                patterns:
                    - '*'
