# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileNotice: Part of the FreeCAD project.


# Configure Dependabot to scan the constraints.txt file that it will find in the root of this repo

version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/Data/Python/Constraints"
    schedule:
      interval: "weekly"
    groups:
      all-deps:
        patterns:
          - "*"
