
blank_issues_enabled : false

contact_links:

-   about : Join the community on our Discord.
    name : ğŸ’¬â€‚ğ——ğ—¶ğ˜€ğ—°ğ—¼ğ—¿ğ—±
    url : https://discord.gg/U52CaAQ7j3

-   about : Join the community on our Forum.
    name : ğŸ’¬â€‚ğ—™ğ—¼ğ—¿ğ˜‚ğ—º
    url : https://forum.freecad.org/viewforum.php?f=65

-   about : Start building with our template.
    name : ğŸ“¦â€‚ğ—§ğ—²ğ—ºğ—½ğ—¹ğ—®ğ˜ğ—²
    url : https://github.com/FreeCAD/Addon-Template

-   about : Learn about addons in our academy.
    name : ğŸ“â€‚ğ—”ğ—°ğ—®ğ—±ğ—²ğ—ºğ˜†
    url : https://github.com/FreeCAD/Addon-Academy

